name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      clang_version:
        description: 'Choose clang version '
        required: true
        default: '12'
        type: choice
        options:
          - '12'
          - '18'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Check Disk Space
        run: df -h
        
      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y make patch curl git llvm lld build-essential \
            libncurses-dev libssl-dev bc flex bison rsync kmod cpio python3 \
            gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu ccache

      - name: Setup Official Android Clang
        run: |
          if [ "${{ github.event.inputs.clang_version }}" = "12" ]; then
            echo "--- Setup Official Android Clang 12 (r416183b) ---"
            mkdir -p $GITHUB_WORKSPACE/clang
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-release/clang-r416183b.tar.gz
            tar -xzf clang-r416183b.tar.gz -C $GITHUB_WORKSPACE/clang
            rm clang-r416183b.tar.gz
          else
            echo "--- Setup Official Android Clang 18 (r522817) ---"
            mkdir -p $GITHUB_WORKSPACE/clang
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main-release/clang-r522817.tar.gz
            tar -xzf clang-r522817.tar.gz -C $GITHUB_WORKSPACE/clang
            rm clang-r522817.tar.gz
          fi
          echo "$GITHUB_WORKSPACE/clang/bin" >> $GITHUB_PATH

      - name: Verify Clang Version
        run: clang --version
        
      - name: Run Build Script
        run: |
          wget https://raw.githubusercontent.com/xxblebleblexx/kernel_builder_action/refs/heads/$GITHUB_REF_NAME/kernel.sh
          chmod +x kernel.sh
          sh kernel.sh

      - name: Prepare image.gz
        run: |
          mkdir -p dir_image_gz
          find . -type f \( -name "image.gz" -o -name "Image.gz" \) -exec cp {} dir_image_gz/ \;
      
      - name: Upload image.gz
        uses: actions/upload-artifact@v4
        with:
          name: image-gz
          path: dir_image_gz/

      - name: Prepare image.gz-dtb
        run: |
          mkdir -p dir_dtb
          find . -type f \( -name "image.gz-dtb" -o -name "Image.gz-dtb" \) -exec cp {} dir_dtb/ \;
      
      - name: Upload image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: image-gz-dtb
          path: dir_dtb/

      - name: Prepare Image
        run: |
          mkdir -p dir_image
          find . -type f -name "Image" -exec cp {} dir_image/ \;
      
      - name: Upload Image
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: dir_image/
